(function(){
  window.GAME_CONFIG = {
    RENDER: { TILE_SIZE: 16, CANVAS_WIDTH:800, CANVAS_HEIGHT:600 },
    TILE: { FLOOR:0, WALL:1, EXIT:2, ENTRY:3 },
    PATHFIND: { REPATH_MS:500, DIAGONAL:false },
    DEBUG: { SHOW_GRID:false, SHOW_PATH:false }
  };

  window.TILE_SIZE = GAME_CONFIG.RENDER.TILE_SIZE;
  window.TILE = GAME_CONFIG.TILE;
  window.PATHFIND = GAME_CONFIG.PATHFIND;
  window.DEBUG = GAME_CONFIG.DEBUG;
})();
